# Generated by Django 6.0.5 on 2026-05-28 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staffprofile",
            old_name="Department",
            new_name="department",
        ),
    ]
