# Generated by Django 6.0.5 on 2026-05-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="medical_notes",
            field=models.TextField(
                blank=True, help_text="Visible to clinical staff only"
            ),
        ),
    ]
